[package]
name = "frost_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
frost-dalek = { git = "https://github.com/isislovecruft/frost-dalek.git" }
clap = { version = "4.0", features = ["derive"] }